version: '3.9'

networks:
  web_network:
    name: vhprovincial
    driver: bridge

services:
  hyggeoaapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vhprovincial
    restart: always
    ports:
      - 8088:8088
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - web_network
